### ISSUE TITLE
Unique companion error

### ISSUE THREAD

**Issue by DragonSin91** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#12]
I've just recruited Gecko the Silurian Outcast, and I'm experiencing a bug where attempting to talk to her zooms the game in as if to start dialogue, but then zooms back out without any conversation happening. There's also an error listed in the console when the above occurs.
![20210211152714_1](https://user-images.githubusercontent.com/78672951/107602532-00cc4c00-6c7e-11eb-8e36-ec58df40ea55.jpg)

**Comment by Rythian2277** [comment]
By any chance are you using the xNVSE (Version 6+) of NVSE? If so, Fallout Who Vegas (Even the complete edition) isn't compatible with xNVSE at this time but we are working on a patch.

**Comment by DragonSin91** [comment]
I am using the xNVSE version, but I'm also using Duck's test patch. Problem is, even when using older versions of the mod (with Xoanon's patches), as well as the previous version of NVSE, the issue still occurs.

**Comment by Rythian2277** [comment]
Unfortunately Gecko and her associated questline are some of the most broken aspects of FWV, I will take a look into addressing the possibility of patching her code but for the time being this isn't solvable.
