### ISSUE TITLE
TARDIS controls unusuable after ship battle

### ISSUE THREAD

**Issue by muddyrudder** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#15]
After a ship battle, my zigzag plotter becomes totally unclickable and unusable. This persists if I reload a save and only resolves itself when I close the game and open it again.

**Comment by Rythian2277** [comment]
Engine issue with New Vegas not properly executing scripts. I will look into the issue and try to add a redundancy to the system but unfortunately new vegas is new vegas.
