### ISSUE TITLE
Exterior Improvements not Installing Correctly

### ISSUE THREAD

**Issue by Mackquinn00** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#19]
When installing the complete edition via NMM, the enhanced exterior option at the beginning is treated as a required option and cannot be deselected. Furthermore, both this option and the 2005 exterior replacer do not install correctly. The exteriors remain unchanged from how they are normally in the mod. However, when the original 2010 and 2014 exteriors replacement mod was downloaded and installed through NMM it worked perfectly fine.
Edit: I have since found the working version of Jack's 2005 exterior mod as well and it works on its own too.

**Comment by Rythian2277** [comment]
The reason this occurs is due to an incorrect file path in Jack's mod, meaning the mod has to be placed in the exact right location for it to work.

The fixed mod is lined up as a part of the next release.

**Comment by thestubborn** [comment]
Doesn't work on MO2.
