### ISSUE TITLE
FWV Intro Cutscene textures may not install correctly

### ISSUE THREAD

**Issue by Rythian2277** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#2]
*Reported by Jack (J!M!B#1345)*

The textures for the FWV intro scene may not install correctly, may need a review of how each file installs with v1.1.0

**Comment by JiMiB03** [comment]
![Fallout_ New Vegas 12_11_2020 20_06_33](https://user-images.githubusercontent.com/48562273/98993116-f76c0000-2525-11eb-833f-76cc52e91000.png)
![Fallout_ New Vegas 12_11_2020 20_06_40](https://user-images.githubusercontent.com/48562273/98993118-f89d2d00-2525-11eb-9993-cfd6732f8047.png)
![Fallout_ New Vegas 12_11_2020 20_06_18](https://user-images.githubusercontent.com/48562273/98993122-fa66f080-2525-11eb-9def-cd79e7fcaabb.png)

**Comment by Rythian2277** [comment]
For some reason, it seems that the texture files didn't unzip properly. Will be patched in v1.0.5
