### ISSUE TITLE
TTW (Tardis Not Spawning) Vault 101

### ISSUE THREAD

**Issue by Apoclost** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#21]
As the title suggest I selected the TTW patch and started a new game, Complete Vault 101 and the Tardis is not spawning/script may not be running I have tried uninstalling and reinstalling the mod. Reinstalling TTW and a couple other solutions from the Fallout Who Discord. None of them worked,

Here is my current load order:
FalloutNV.esm
DeadMoney.esm
HonestHearts.esm
OldWorldBlues.esm
LonesomeRoad.esm
GunRunnersArsenal.esm
Fallout3.esm
Anchorage.esm
ThePitt.esm
BrokenSteel.esm
PointLookout.esm
Zeta.esm
CaravanPack.esm
ClassicPack.esm
MercenaryPack.esm
TribalPack.esm
TaleOfTwoWastelands.esm
YUPTTW.esm
Fallout Who Vegas TTW Addon.esp
Armored, armored vault 101 jumpsuit..esp
CASM with MCM.esp
DC Armories Expanded TTW.esp
FNVLODGen.esp
ISControl.esm
JIP Improved Recipe Menu.esp
LootMenu.esp
pipboy2500_edisleado.esp
populatedcasino.esp
The Mod Configuration Menu.esp
The Weapon Mod Menu.esp
TTWMergedQuests.esp
fwv Patch Regeneration Deuglifier.esp
fwv.esm
fwv.esp
fwvDeadMoneySonic.esp
FWVPerceptionFilterImprovements.esp
fwvSpyduckThemeUpdates.esm
fwvSpyduckThemeUpdates.esp
fwvThemeShalka.esp
FWVTimeCrackNoDisable.esp
FwvTweak.esp
fwvXoanon.esm
fwvXoanon.esp
fwvXoanon_PersPref.esp
fwvXoanonDeuglifierCompat.esp
fwvXoanonLaserScrewdriverEdits.esp
fwvXoanonNoSPECIALRandomizeOnRegen.esp
fwvXoanonOutfitBonuses.esp
fwvXoanonRevisedCompanions.esp
TimeLordArsenal.esp

I am also running the latest version of xNVSE. If that matters at all. 
I hope providing this load order give some insight into it. I hope it something that can be resolved quickly.

-Apoclost

**Comment by Rythian2277** [comment]
The load order for this game seems to be loading a few FWV plugins before FWV itself is loaded, I suggest to anyone encountering this issue to run LOOT and reorder their plugin list.
