### ISSUE TITLE
Bug with potential fix Coral Theme Scanner/Console Computer inaccessible.

### ISSUE THREAD

**Issue by sethhackley** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#23]
[Coral_theme_update_and_fixes-50231-1-0.zip](https://github.com/Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition/files/9485401/Coral_theme_update_and_fixes-50231-1-0.zip)
I was playing fallout who vegas last night and switched over to the coral theme. The Console computer/scanner became inaccessable thus soft locking me. I do have an ESP that fixes this issue that worked with the non-complete version of fallout who vegas but complete edition says it's incompatible.

**Comment by Rythian2277** [comment]
I will look into including this for v1.2.1
