### ISSUE TITLE
Enhancement: Add Edwardian Classic Console Room, Void's Whisper Console Room, And Ancient Gallifreyan Console Room

### ISSUE THREAD

**Issue by sethhackley** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#24]
Add Edwardian Classic Console room, Void's Whisper Console Room, and Ancient Gallifreyan Console Room

https://www.nexusmods.com/newvegas/mods/66565

https://www.nexusmods.com/newvegas/mods/59737

https://www.nexusmods.com/newvegas/mods/61310?tab=files

**Comment by Rythian2277** [comment]
These add-on's aren't compatible with the latest version of Fallout Who Vegas, hence the lack of inclusion. We did look at adding these in the first edition of the mod but they caused too many compatibility issues in the long term.
