### ISSUE TITLE
Same Face bug.

### ISSUE THREAD

**Issue by ghost** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#25]
Keep getting the same face every time I regen. Reloading doesn't seem to work.  Turning off deuglifier plugin seem to get rid of it, I think there might be an issue with xoanon compat patch  and deug.

**Comment by Rythian2277** [comment]
The Deuglifier and Xoanon's patch were designed to keep player characters looking human, this may be an issue with the root code of the plugins so unfortunately a **community** patch would be needed to adjust this issue.
