### ISSUE TITLE
Textures not working properly

### ISSUE THREAD

**Issue by FuzzyLeo** [Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition#3]
![image](https://user-images.githubusercontent.com/23579757/99112635-e1be0f80-25e5-11eb-9b3e-ec9e8396fb40.png)
As i look around it cycles through a bunch of textures, except on non modded objects.

**Comment by Rythian2277** [comment]
For some reason, it seems that the texture files didn't unzip properly. Will be patched in v1.0.5

**Comment by Rythian2277** [comment]
Resolved as of [Missing Textures](https://github.com/Fallout-Who-Vegas/Fallout-Who-Vegas-Complete-Edition/commit/7594cd40c8d376269e71f11bae009d1af6385447)
